### ISSUE TITLE
Epic: As a user, I want a simple way to sign-in and sign-up to the platform with google sign-on to ensure my account is created correctly.

### ISSUE THREAD

**Issue by alliemontiague** [CEN3031-Group-3h/Sapphire-Project08-3h#1]
User stories:
- [ ] As a user, I want to be able to login once and be able to have access to the platform for numerous hours until I have to login again.
- [ ] As a user, I would like to sign in both with Google Sign-on and with my email address and chosen password.
- [ ] As a professor, I want a simplified, quick sign-on process where my students can utilize their google accounts, diminishing the need to create a separate account for this platform, to access the Code-Sparks platform with a google authentication process.
Tasks:
- [ ] special role verification - submit verification requests
- [ ] special role verification - view verification request
- [ ] special role verification - Create Additional Roles 
- [ ] special role verification - send email to admin
- [ ] login page - support password authentication
- [ ] login page - link sign in and sign up pages
- [ ] change color schema - Change the colors to increase contrast
- [ ] change color scheme - change on hover features

Acceptance Criteria:
- [ ] users with special roles can seamlessly submit verification requests
- [ ] admins can view and manage verification requests
- [ ] automated emails are sent upon any changes
- [ ] login page supports google sign-on methods
- [ ] interactive elements show change when hovered
