### ISSUE TITLE
Epic: As a website administrator, I want comprehensive tools and features to manage the website efficiently, and ensure a smooth experience for all users.

### ISSUE THREAD

**Issue by alliemontiague** [CEN3031-Group-3h/Sapphire-Project08-3h#2]
User Stories

- [x] As a website administrator, I want the ability to add, modify, or remove user accounts to maintain control over who has access to various parts of the website.
- [ ] As a website administrator, I would like to receive notifications about potential security threats or breaches, so I can address issues promptly and safeguard the website's integrity.
- [ ] As a website administrator, I desire a seamless integration with analytical tools, enabling me to monitor site traffic and user behavior, ensuring I can make data-driven decisions to enhance user experience on the platform.

Tasks:

- [x] special role verification - design a role assignment interface(2.5)
- [x] special role verification see permissions based on roles(2)
- [x] special role verification - test role-based access control(2)
- [x] #7
- [x] Seamless Google Integration - Design a Google-friendly user experience [2]
- [x] #8

Acceptance criteria:
- website administrator has ability to add, modify, or remove user accounts
- website administrator receives notifications about potential security threats
- website administrator had seamless integration of analytical tools
- seamless google integration that is user-friendly

**Comment by alliemontiague** [comment]
- Researched google API's in order to implement [10] task
