### ISSUE TITLE
Epic: As a professor, I would want all my learning materials from Code-sparks to be integrated into google classroom seamlessly,not having to worry about configuration besides simple access toggle settings.

### ISSUE THREAD

**Issue by smclaughlin1** [CEN3031-Group-3h/Sapphire-Project08-3h#3]
User stories

- [x] As a professor, I want to be able to upload grades and assignments from Code-sparks.org to Google Classroom.

- [ ] As a student, in an event where I lose internet connection, I would want my data to be saved. 
- [ ] I want my working environment and code blocks saved ideally up to <1min of a connection loss.
- [ ] As a student, I want to easily turn in assignments on a LMS.

Tasks:

- [x] code sparks access - design a user-friendly interface for code sparks
- [x] code sparks access - integrate with code sparks api or database
- [x] code sparks access - test accessibility and functionality
- [x] upload grades/assignments to google classroom - Implement a grade and assignment upload system 
- [ ] upload grades/assignments to google classroom  - Integrate with Google Classroom for automatic uploads 
- [ ] upload grades/assignments to google classroom -  Design an interface for manual uploads and edits 
- [ ] upload grades/assignments to google classroom - Test uploads to ensure accuracy [2]

Acceptance Criteria:

- [ ] professors can seamlessly upload grades and assignments without data inconsistencies

- [ ] data is preserved during connectivity issues
- [ ] product page effectively displays items
- [ ] adjustments to view are functional and visually appealing
- [ ] all features operate smoothly
